import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    alignItems: "center",
    marginBottom: 24,
  },
  thumbnail: {
    width: 180,
    height: 100,
    borderRadius: 10,
    backgroundColor: "#e0e0e0",
    marginBottom: 12,
    resizeMode: "cover",
  },
  sessionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1D4ED8",
    textAlign: "center",
  },
  section: {
    marginBottom: 24,
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1D4ED8",
    marginBottom: 10,
  },
  textNotesInput: {
    minHeight: 60,
    borderColor: "#e5e7eb",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    fontSize: 15,
    color: "#222",
    backgroundColor: "#f3f4f6",
    textAlignVertical: "top",
  },
  drillItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    paddingVertical: 4,
  },
  drillName: {
    marginLeft: 10,
    fontSize: 15,
    color: "#222",
  },
  drillButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  drillButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E0E7FF",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginRight: 8,
  },
  drillButtonText: {
    marginLeft: 6,
    color: "#1D4ED8",
    fontWeight: "600",
    fontSize: 14,
  },
  voiceNoteButton: {
    flex: 1, // Make each button take equal space in the row
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1D4ED8",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    marginBottom: 10,
    justifyContent: "center", // Center icon and text
    marginRight: 8, // Add spacing between buttons (except last)
  },
  voiceNoteButtonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
    marginLeft: 8,
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#10B981",
    paddingVertical: 12,
    borderRadius: 8,
    justifyContent: "center",
    marginTop: 10,
  },
  shareButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft:8,
  },
  drillButtonFullWidth: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E0E7FF",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 10,
    width: "100%",
    justifyContent: "center",
  },
  modalOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 22,
    width: 320,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 5,
  },
  modalTitle: {
    fontWeight: "bold",
    fontSize: 18,
    marginBottom: 14,
    color: "#1D4ED8",
    textAlign: "center",
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    marginBottom: 14,
    padding: 10,
    fontSize: 16,
    color: "#222",
    backgroundColor: "#f3f4f6",
  },
  iconRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 18,
  },
  iconOption: {
    marginHorizontal: 10,
    borderWidth: 2,
    borderColor: "transparent",
    borderRadius: 8,
    padding: 6,
  },
  iconOptionSelected: {
    borderColor: "#1D4ED8",
    backgroundColor: "#E0E7FF",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  modalAction: {
    marginLeft: 18,
  },
  modalCancel: {
    color: "#888",
    fontSize: 16,
  },
  modalAdd: {
    color: "#1D4ED8",
    fontWeight: "bold",
    fontSize: 16,
  },
});